CREATE TABLE mytable(
   Name       VARCHAR(21) NOT NULL PRIMARY KEY
  ,PrizeMoney NUMERIC(7,2) NOT NULL
);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Luke Humphries',1684.25);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Michael Smith',883.5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Michael van Gerwen',812.5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Rob Cross',568.75);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Luke Littler',558.5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Dave Chisnall',532);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Jonny Clayton',506);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Stephen Bunting',483);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Gerwyn Price',477.5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Damon Heta',474);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Dimitri Van den Bergh',471.25);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Nathan Aspinall',439);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Gary Anderson',437.5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Danny Noppert',431.75);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Chris Dobey',427.25);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('James Wade',423.75);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Peter Wright',414.5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Josh Rock',408.5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Ryan Searle',395.25);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Andrew Gilding',375.5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Ross Smith',375);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Martin Schindler',365);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Joe Cullen',364.25);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Mike De Decker',336);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Dirk van Duijvenbode',315.75);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Daryl Gurney',314.25);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Gabriel Clemens',301.75);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Gian van Veen',281);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Ritchie Edhouse',275.25);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Brendan Dolan',268.5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Krzysztof Ratajski',261.25);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Raymond van Barneveld',256.25);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Ricardo Pietreczko',245.75);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Luke Woodhouse',239.75);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Ryan Joyce',234.5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Jermaine Wattimena',212.75);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Martin Lukeman',199.5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Scott Williams',190.75);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Cameron Menzies',179);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Jose de Sousa',174);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Kim Huybrechts',157);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Mickey Mansell',143.25);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Callan Rydz',139);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Madars Razma',131.75);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Ricky Evans',129.25);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Jim Williams',125.75);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Richard Veenstra',112.25);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('William O''Connor',111.5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Alan Soutar',110);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Kevin Doets',108.5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Keane Barry',107.75);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Niels Zonneveld',103.75);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Florian Hempel',96.5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Steve Beaton',96.5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Matt Campbell',95.5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Mensur Suljovic',89.75);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Ian White',84.75);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Wessel Nijman',82);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Boris Krcmar',85);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Simon Whitlock',84.25);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Mervyn King',79.5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Ryan Meikle',72);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Jamie Hughes',72.75);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Adam Gawlas',68.75);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Stephen Burton',64);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Lee Evans',66.75);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Dylan Slevin',65.5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Karel Sedlacek',60.75);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Vincent van der Voort',63.5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Rowby-John Rodriguez',58.75);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Maik Kuivenhoven',56.5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Wesley Plaisier',48);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Jeffrey De Zwaan',51);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Daniel Klose',47.25);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Robert Owen',45.25);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Connor Scutt',42);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Nick Kenny',43.75);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Keegan Brown',42.75);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Dom Taylor',39.5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Jeffrey Sparidaans',41.5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Graham Hall',39.5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Thibault Tricole',35.75);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Arron Monk',37.75);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Jeffrey de Graaf',30);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Graham Usher',32.25);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Jurjen van der Velde',32.25);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Chris Landman',28.75);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('James Hurrell',27.75);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Mario Vandenbogaerde',24.5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Pascal Rupprecht',26.5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Andy Baetens',24.5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Josh Payne',23.5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Berry van Peer',23.5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Adrian Lewis',22.5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Nathan Rafferty',22.25);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Steve Lennon',22);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Radek Szaganski',21.75);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Lukas Wenig',21.5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Owen Roelofs',21);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Danny van Trijp',20.5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Callum Goffin',20.25);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Christian Kist',19.75);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Adam Warner',19.5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Patrick Geeraets',19);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Matthew Dennant',19);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Geert Nentjes',19);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Darren Beveridge',18.75);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Adam Smith-Neale',18.75);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Jitse Van der Wal',18.25);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Benjamin Reus',18);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Ronny Huybrechts',17.75);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Andy Boulton',17);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Danny Lauby',17);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Robert Grundy',16.5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Robbie Knops',16.25);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Christian Perez',15.5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('George Killington',14.5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Owen Bates',14);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Brett Claydon',13.75);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Martijn Dragt',13.5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Adam Hunt',13.5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Darryl Pilgrim',13);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Rhys Griffin',13);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Stefan Bellmont',12.5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Danny Jansen',12.5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Haupai Puha',12.5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Jelle Klaasen',11.75);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('William Borland',11.5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Leighton Bennett',11.5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Leonard Gates',10.5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Franz Roetzsch',10.5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Lee Cocks',10);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Cam Crabtree',10);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('John Henderson',8.5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Jacques Labre',8.25);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Kai Gotthardt',8.25);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Richie Burnett',7.5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Paul Krohne',7.5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Tim Wolters',7.5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Joshua Richardson',7.5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Justin Hood',7);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Michele Turetta',6);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Jamie Atkins',5.5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Beau Greaves',5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Lourence Ilagan',5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Noa-Lynn van Leuven',5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Jimmy van Schie',5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Sebastian Bialecki',5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Romeo Grbavac',4.75);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Ted Evetts',4.5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Oskar Lukasiak',4.5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Pavel Drtil',4);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Jules van Dongen',4);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Marko Kantele',3.75);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Cor Dekker',3.75);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Johan Engstrom',3.75);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Kevin Troppmann',3.75);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Michael Unterbuchner',3.75);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Jiri Brejcha',2.5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Anton Ostlund',2.5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Bruno Stoeckli',2.5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Roger Hertig',2.5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Shane McGuirk',2.5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Alberto Bezjian',2.5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Max Hopp',2.5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Niko Springer',2.5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Matthias Ehlers',2.5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Jan Dueckers',2.5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Marvin van Velzen',2.5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Moreno Blom',2.5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Moritz Hilger',2.5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Darius Labanauskas',2.5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Andreas Harrysson',2.5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Scott Mitchell',2.5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Dragutin Horvat',2.25);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Rene Eidams',2.25);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Aden Kirk',2);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Thomas Lovely',2);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Jarred Cole',1.5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Joe Croft',1.5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Michael Taylor',1.5);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Daniel Markovsky',1.25);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Michal Smejda',1.25);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Patrik Kovacs',1.25);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Alex Fehlmann',1.25);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Marcel Walpen',1.25);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Nandor Pres',1.25);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Andras Csoka',1.25);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Gyorgy Jehirszki',1.25);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Janos Vegso',1.25);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Brian Raman',1.25);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Francois Schweyen',1.25);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Jody Tobback',1.25);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Luc Bogaert',1.25);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Krzysztof Kciuk',1.25);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Benjamin Pratnemer',1.25);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Nico Blum',1.25);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Damian Mol',1.25);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Teemu Harju',1.25);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Christopher Toonders',1.25);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Daniel Larsson',1.25);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Christian Goedl',1.25);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Dominik Haberl',1.25);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Hannes Schnier',1.25);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Zoran Lerchbacher',1.25);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Arno Merk',1.25);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Alexander Masek',1.25);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Patrick Klingelhoefer',1.25);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Oliver Mueller',1.25);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Viktor Tingstrom',1.25);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Vitezslav Sedlak',1.25);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Born van Put',1.25);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Geert De Vos',1.25);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Jeroen Caron',1.25);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Steven Strobbe',1.25);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Dominik Gruellich',1);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Alexander Merkx',1);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Stefaan Henderyck',1);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Reece Colley',1);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Bradley Brooks',1);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Harry Lane',1);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Jack Male',1);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Jenson Walker',1);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('John Haines',1);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Ron Meulenkamp',1);
INSERT INTO mytable(Name,PrizeMoney) VALUES ('Tom Lonsdale',1);
